- name: Run pacman -Syu equivalent
  community.general.pacman:
    upgrade: true
    update_cache: true
  when: ansible_facts['distribution'] == "Archlinux"
  tags:
    - molecule-idempotence-notest

- name: Install pacman packages
  community.general.pacman:
    name:
      - nodejs
      - npm
      - gcc
      - fakeroot
      - sudo
      - git
      - ripgrep
    state: present
  when: ansible_facts['distribution'] == "Archlinux"

- name: Update ca certificates
  command: update-ca-certificates --fresh
  when: ansible_facts['distribution'] == "Ubuntu"
  tags:
    - molecule-idempotence-notest

- name: Enable neovim-ppa
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install apt packages
  ansible.builtin.apt:
    pkg:
      - nodejs
      - npm
      - ripgrep
      - neovim
      - sudo
    state: present
    update_cache: true
  when: ansible_facts['distribution'] == "Ubuntu"
