- name: Run pacman -Syu equivalent
  community.general.pacman:
    upgrade: true
    update_cache: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Install pacman packages
  community.general.pacman:
    name:
      - nodejs
      - npm
    state: present
  when: ansible_facts['distribution'] == "Archlinux"

- name: Install apt packages
  ansible.builtin.apt:
    pkg:
      - nodejs
      - npm
    state: present
    update_cache: true
  when: ansible_facts['distribution'] == "Ubuntu"
