---
# tasks file for editor

- name: Install packages
  ansible.builtin.include_tasks: install_deps.yml

- name: Setup plum user
  ansible.builtin.include_role:
    name: user
    tasks_from: setup_plum_user.yml

- name: Setup nvim
  ansible.builtin.include_tasks: setup_nvim.yml
